import UIKit
import PDFKit

final class PDFReportGenerator {
    struct ReportConfig {
        var patientName: String
        var startDate: Date
        var endDate: Date
        var includeEpisodeSummary: Bool = true
        var includeCalendarHeatmap: Bool = true
        var includeSymptomBreakdown: Bool = true
        var includeTriggerCorrelations: Bool = true
        var includeMedicationUsage: Bool = true
        var includeWeatherCorrelation: Bool = true
        var includeSleepCorrelation: Bool = true
        var includeFullLog: Bool = true
    }

    private let pageWidth: CGFloat = 612 // US Letter
    private let pageHeight: CGFloat = 792
    private let margin: CGFloat = 50
    private let accentColor = UIColor(red: 0.17, green: 0.24, blue: 0.31, alpha: 1.0) // #2C3E50
    private let tealColor = UIColor(red: 0.10, green: 0.74, blue: 0.61, alpha: 1.0) // #1ABC9C

    func generateReport(
        config: ReportConfig,
        episodes: [Episode],
        medications: [Medication],
        triggerCorrelations: [TriggerCorrelation]
    ) -> Data {
        let pageRect = CGRect(x: 0, y: 0, width: pageWidth, height: pageHeight)
        let renderer = UIGraphicsPDFRenderer(bounds: pageRect)

        let data = renderer.pdfData { context in
            // Title page
            context.beginPage()
            var y = drawTitlePage(context: context, config: config)

            // Episode summary
            if config.includeEpisodeSummary {
                y = checkPageBreak(context: context, y: y, needed: 200)
                y = drawEpisodeSummary(context: context, y: y, episodes: episodes, config: config)
            }

            // Symptom breakdown
            if config.includeSymptomBreakdown {
                y = checkPageBreak(context: context, y: y, needed: 200)
                y = drawSymptomBreakdown(context: context, y: y, episodes: episodes)
            }

            // Trigger correlations
            if config.includeTriggerCorrelations && !triggerCorrelations.isEmpty {
                y = checkPageBreak(context: context, y: y, needed: 200)
                y = drawTriggerSection(context: context, y: y, correlations: triggerCorrelations)
            }

            // Medication usage
            if config.includeMedicationUsage && !medications.isEmpty {
                y = checkPageBreak(context: context, y: y, needed: 200)
                y = drawMedicationSection(context: context, y: y, medications: medications, episodes: episodes)
            }

            // Full episode log
            if config.includeFullLog {
                context.beginPage()
                _ = drawFullLog(context: context, episodes: episodes)
            }

            // Disclaimer page
            context.beginPage()
            _ = drawDisclaimer(context: context)
        }

        return data
    }

    // MARK: - Title Page

    private func drawTitlePage(context: UIGraphicsPDFRendererContext, config: ReportConfig) -> CGFloat {
        var y = margin + 60

        let titleAttrs: [NSAttributedString.Key: Any] = [
            .font: UIFont.systemFont(ofSize: 28, weight: .bold),
            .foregroundColor: accentColor
        ]
        let title = "Symptom Report"
        title.draw(at: CGPoint(x: margin, y: y), withAttributes: titleAttrs)
        y += 40

        let nameAttrs: [NSAttributedString.Key: Any] = [
            .font: UIFont.systemFont(ofSize: 20, weight: .medium),
            .foregroundColor: accentColor
        ]
        let name = "for \(config.patientName)"
        name.draw(at: CGPoint(x: margin, y: y), withAttributes: nameAttrs)
        y += 35

        let dateAttrs: [NSAttributedString.Key: Any] = [
            .font: UIFont.systemFont(ofSize: 14),
            .foregroundColor: UIColor.darkGray
        ]
        let dateRange = "\(config.startDate.shortDateString) — \(config.endDate.shortDateString)"
        dateRange.draw(at: CGPoint(x: margin, y: y), withAttributes: dateAttrs)
        y += 20

        let generatedAttrs: [NSAttributedString.Key: Any] = [
            .font: UIFont.systemFont(ofSize: 12),
            .foregroundColor: UIColor.gray
        ]
        let generated = "Generated by Aura Symptom Tracker on \(Date().shortDateString)"
        generated.draw(at: CGPoint(x: margin, y: y), withAttributes: generatedAttrs)
        y += 40

        // Horizontal line
        let linePath = UIBezierPath()
        linePath.move(to: CGPoint(x: margin, y: y))
        linePath.addLine(to: CGPoint(x: pageWidth - margin, y: y))
        tealColor.setStroke()
        linePath.lineWidth = 2
        linePath.stroke()
        y += 30

        return y
    }

    // MARK: - Episode Summary

    private func drawEpisodeSummary(context: UIGraphicsPDFRendererContext, y: CGFloat, episodes: [Episode], config: ReportConfig) -> CGFloat {
        var currentY = y

        currentY = drawSectionHeader(at: currentY, title: "Episode Summary")

        let filteredEpisodes = episodes.filter {
            $0.timestamp >= config.startDate && $0.timestamp <= config.endDate
        }

        let bodyAttrs: [NSAttributedString.Key: Any] = [
            .font: UIFont.systemFont(ofSize: 12),
            .foregroundColor: UIColor.darkGray
        ]

        let totalEpisodes = filteredEpisodes.count
        let avgPain = filteredEpisodes.isEmpty ? 0 :
            Double(filteredEpisodes.reduce(0) { $0 + $1.painLevel }) / Double(totalEpisodes)
        let daysWithEpisodes = Set(filteredEpisodes.map { $0.timestamp.startOfDay }).count
        let dayRange = max(1, Calendar.current.dateComponents([.day], from: config.startDate, to: config.endDate).day ?? 1)

        let stats = [
            "Total episodes: \(totalEpisodes)",
            "Average pain level: \(String(format: "%.1f", avgPain))/10",
            "Days with episodes: \(daysWithEpisodes) of \(dayRange) days",
            "Episode frequency: \(String(format: "%.1f", Double(totalEpisodes) / Double(dayRange) * 30)) per month",
        ]

        for stat in stats {
            stat.draw(at: CGPoint(x: margin + 10, y: currentY), withAttributes: bodyAttrs)
            currentY += 20
        }

        currentY += 20
        return currentY
    }

    // MARK: - Symptom Breakdown

    private func drawSymptomBreakdown(context: UIGraphicsPDFRendererContext, y: CGFloat, episodes: [Episode]) -> CGFloat {
        var currentY = y
        currentY = drawSectionHeader(at: currentY, title: "Symptom Frequency")

        var symptomCounts: [String: Int] = [:]
        for episode in episodes {
            for symptom in episode.symptoms ?? [] {
                symptomCounts[symptom.name, default: 0] += 1
            }
        }

        let sorted = symptomCounts.sorted { $0.value > $1.value }
        let bodyAttrs: [NSAttributedString.Key: Any] = [
            .font: UIFont.systemFont(ofSize: 12),
            .foregroundColor: UIColor.darkGray
        ]

        for (name, count) in sorted.prefix(15) {
            let pct = episodes.isEmpty ? 0 : Double(count) / Double(episodes.count) * 100
            let line = "\(name): \(count) episodes (\(String(format: "%.0f", pct))%)"
            line.draw(at: CGPoint(x: margin + 10, y: currentY), withAttributes: bodyAttrs)
            currentY += 18
        }

        currentY += 20
        return currentY
    }

    // MARK: - Trigger Section

    private func drawTriggerSection(context: UIGraphicsPDFRendererContext, y: CGFloat, correlations: [TriggerCorrelation]) -> CGFloat {
        var currentY = y
        currentY = drawSectionHeader(at: currentY, title: "Trigger Correlations")

        let bodyAttrs: [NSAttributedString.Key: Any] = [
            .font: UIFont.systemFont(ofSize: 12),
            .foregroundColor: UIColor.darkGray
        ]

        for correlation in correlations.prefix(10) {
            let line = "\(correlation.triggerName): \(String(format: "%.0f", correlation.percentage))% of episodes (\(correlation.confidence.rawValue))"
            line.draw(at: CGPoint(x: margin + 10, y: currentY), withAttributes: bodyAttrs)
            currentY += 18
        }

        currentY += 20
        return currentY
    }

    // MARK: - Medication Section

    private func drawMedicationSection(context: UIGraphicsPDFRendererContext, y: CGFloat, medications: [Medication], episodes: [Episode]) -> CGFloat {
        var currentY = y
        currentY = drawSectionHeader(at: currentY, title: "Medication Usage")

        let bodyAttrs: [NSAttributedString.Key: Any] = [
            .font: UIFont.systemFont(ofSize: 12),
            .foregroundColor: UIColor.darkGray
        ]

        for med in medications {
            let doseCount = med.doses?.count ?? 0
            let line = "\(med.name) (\(med.dosage), \(med.medicationType.rawValue)): \(doseCount) doses"
            line.draw(at: CGPoint(x: margin + 10, y: currentY), withAttributes: bodyAttrs)
            currentY += 18
        }

        currentY += 20
        return currentY
    }

    // MARK: - Full Log

    private func drawFullLog(context: UIGraphicsPDFRendererContext, episodes: [Episode]) -> CGFloat {
        var currentY = margin
        currentY = drawSectionHeader(at: currentY, title: "Full Episode Log")

        let bodyAttrs: [NSAttributedString.Key: Any] = [
            .font: UIFont.systemFont(ofSize: 10),
            .foregroundColor: UIColor.darkGray
        ]
        let boldAttrs: [NSAttributedString.Key: Any] = [
            .font: UIFont.systemFont(ofSize: 10, weight: .semibold),
            .foregroundColor: UIColor.darkGray
        ]

        for episode in episodes.sorted(by: { $0.timestamp > $1.timestamp }) {
            currentY = checkPageBreak(context: context, y: currentY, needed: 60)

            let dateStr = episode.timestamp.shortDateTimeString
            let painStr = "Pain: \(episode.painLevel)/10 (\(episode.painCategory.rawValue))"
            "\(dateStr) — \(painStr)".draw(at: CGPoint(x: margin + 10, y: currentY), withAttributes: boldAttrs)
            currentY += 16

            if let symptoms = episode.symptoms, !symptoms.isEmpty {
                let symptomsStr = "Symptoms: \(symptoms.map(\.name).joined(separator: ", "))"
                symptomsStr.draw(at: CGPoint(x: margin + 20, y: currentY), withAttributes: bodyAttrs)
                currentY += 14
            }

            if let triggers = episode.triggers, !triggers.isEmpty {
                let triggersStr = "Triggers: \(triggers.map(\.name).joined(separator: ", "))"
                triggersStr.draw(at: CGPoint(x: margin + 20, y: currentY), withAttributes: bodyAttrs)
                currentY += 14
            }

            if let notes = episode.notes, !notes.isEmpty {
                let notesStr = "Notes: \(notes)"
                notesStr.draw(at: CGPoint(x: margin + 20, y: currentY), withAttributes: bodyAttrs)
                currentY += 14
            }

            currentY += 8
        }

        return currentY
    }

    // MARK: - Disclaimer

    private func drawDisclaimer(context: UIGraphicsPDFRendererContext) -> CGFloat {
        var y = margin + 200

        let titleAttrs: [NSAttributedString.Key: Any] = [
            .font: UIFont.systemFont(ofSize: 14, weight: .semibold),
            .foregroundColor: UIColor.gray
        ]
        "Disclaimer".draw(at: CGPoint(x: margin, y: y), withAttributes: titleAttrs)
        y += 25

        let bodyAttrs: [NSAttributedString.Key: Any] = [
            .font: UIFont.systemFont(ofSize: 11),
            .foregroundColor: UIColor.gray
        ]

        let paragraphs = [
            "This report was generated by the patient using Aura Symptom Tracker.",
            "It is intended as a discussion aid and does not constitute a medical diagnosis.",
            "All data is self-reported by the patient and has not been independently verified.",
            "Pattern correlations are statistical observations and do not establish causation.",
            "Please review this data in the context of the patient's full medical history.",
        ]

        for paragraph in paragraphs {
            let rect = CGRect(x: margin, y: y, width: pageWidth - margin * 2, height: 40)
            paragraph.draw(in: rect, withAttributes: bodyAttrs)
            y += 22
        }

        return y
    }

    // MARK: - Helpers

    private func drawSectionHeader(at y: CGFloat, title: String) -> CGFloat {
        let attrs: [NSAttributedString.Key: Any] = [
            .font: UIFont.systemFont(ofSize: 16, weight: .bold),
            .foregroundColor: accentColor
        ]
        title.draw(at: CGPoint(x: margin, y: y), withAttributes: attrs)

        let lineY = y + 24
        let linePath = UIBezierPath()
        linePath.move(to: CGPoint(x: margin, y: lineY))
        linePath.addLine(to: CGPoint(x: pageWidth - margin, y: lineY))
        UIColor.lightGray.setStroke()
        linePath.lineWidth = 0.5
        linePath.stroke()

        return lineY + 15
    }

    private func checkPageBreak(context: UIGraphicsPDFRendererContext, y: CGFloat, needed: CGFloat) -> CGFloat {
        if y + needed > pageHeight - margin {
            context.beginPage()
            return margin
        }
        return y
    }
}
